### ISSUE TITLE
Menu seems to have superfluous items

### ISSUE THREAD

**Issue by tammoterhark** [evently-nl/zest-issues#1]
### Expected behavior
Different responses for different menu items

### Actual behavior
4 menu items have only 2 responses

### Steps to reproduce
Open zest, click on menu items

### Limesurvey version used:
Not relevant

![Zest](https://user-images.githubusercontent.com/6483317/55889329-37803980-5bb1-11e9-8aa8-d2a34403cf62.png)

**Comment by evently-nl** [comment]
Zijn verschillende links: 
1e is overzicht, maar deze toont hulpt als je nog niks hebt toegevoegd. Onboarding van volgende versie wordt sowieso vernieuwd, zodat je meteen aan de slag kan.

2e link is servers, 3e surveys, 4e hulp

**Comment by tammoterhark** [comment]
Misschien kun je deze zaken verwerken in een breadcrumb:

Home > [servername] > [surveytitle] >

**Comment by tammoterhark** [comment]
Alle links staan overigens ook in de bovenbalk.

**Comment by evently-nl** [comment]
Tweemaal eens!

**Comment by tammoterhark** [comment]
Als je dat blokje kunt weghalen, heb je meer schermbreedte...
